baseURL = "https://kienpham2000.github.io/blog/"
ignoreFiles = [ "\\.files/README.md$",  ]
defaultContentLanguage = "en"
uglyurls = false
googleAnalytics = "UA-68379-1"
languageCode = "en-us"
title = "Kien Pham Blog"
theme = "Cactus"
publishdir = "docs"
sectionPagesMenu = "main"
relativeURLs = true
