title: Kien Pham
baseURL: "https://kienpham.com/"
ignoreFiles: [ "\\.files/README.md$",  ]
defaultContentLanguage: en
uglyurls: false
googleAnalytics: UA-68379-1
languageCode: en-us
theme: PaperMod # paper Cactus PaperMod
sectionPagesMenu: main
relativeURLs: true
paginate: 100
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Kien Pham"
  keywords: [kien, "kien pham"]
  author: "Kien Pham"
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true
    title: Kien Pham
    subtitle: "Software Engineer based in Orange County, CA."
    imageUrl: "images/kienpham.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Kien Pham photo
    buttons:
      - name: Blog Posts
        url: posts
      - name: Projects
        url: projects

  # home-info mode
  # homeInfoParams:
  #   Title: "Hola \U0001F44B!"
  #   Content: Welcome to my blog

  # socialIcons:
  #   - name: linkedin
  #     url: "https://linkedin.com/in/kpx-pro/"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# required for search
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - identifier: projects
      name: Open Source Projects
      url: /projects/
      weight: 10
    # - identifier: search
    #   name: Search
    #   url: /search/
    #   weight: 10
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
